services:
  
  humpsi.api:
    image: humpsi.api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    depends_on:
      - humpsi.cache
      - humpsi.postgresDb
    hostname: street-code-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - humpsi
  
  humpsi.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  humpsi.postgresDb:
    container_name: humpsiPostgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "humpsiDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    
networks:
  humpsi:
    driver: bridge
  