<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="13.0.1" />
      <PackageReference Include="FluentValidation" Version="12.0.0-preview1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0-preview1" />
      <PackageReference Include="MediatR" Version="12.4.1" />
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="6.0.0-preview.4.21253.5" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.1" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.1" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
      <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
      <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HumPsi.Domain\HumPsi.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Hosting.Abstractions">
        <HintPath>..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\8.0.4\Microsoft.AspNetCore.Hosting.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.AspNetCore.Http.Features">
        <HintPath>..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\8.0.4\Microsoft.AspNetCore.Http.Features.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
